######################站点全局信息，需要部分修改#########################
# Site settings
title: Vincent 
header-img: img/home-bg.jpg
email: vincent.ch.cn@gmail.com
url: "https://chengwenxi.github.io"
description: "1+1=10"
github_username:  chengwenxi
duoshuo_id: vincent-ch
stackoverflow: 7019725 ##Stack Overflow id
##########################上述信息需要您修改########3####################

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
posts_dir: ./_posts
#collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["less","node_modules","Gruntfile.js","package.json","README.md","tmp","unless"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      ["jekyll-paginate"]
#gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink: pretty
paginate: 16
paginate_path: /page/:num
timezone: Asia/Shanghai

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

